# Generated by Django 3.2.24 on 2024-02-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rdesc', models.TextField()),
                ('rimg', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
