# Generated by Django 3.2.24 on 2024-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rv_count',
            field=models.IntegerField(default=1),
        ),
    ]
